dFeed/dFeed/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf.urls import url
from feedMaster.routers import router

urlpatterns = [
    path('admin/', admin.site.urls),
    path('feedreader/', include('feedreader.urls')),
    url(r'^', include(router.urls))
]

dFeed/feedreader/urls.py
from __future__ import absolute_import

from django.urls import path

from .views import (FeedList, Search, EntryList,
                    NumbersUnread, MarkEntryRead,
                    EditFeeds, ExportOpml, UpdateItem)

app_name = 'feedreader'
urlpatterns = [
   path('', view=FeedList.as_view(), name='feed_list'),
   path('entry_list', view=EntryList.as_view(), name='entry_list'),
   path('num_unread', view=NumbersUnread.as_view(), name='num_unread'),
   path('mark_entry_read', view=MarkEntryRead.as_view(), name='mark_entry_read'),
   path('search', view=Search.as_view(), name='search'),
   path('edit_feeds', view=EditFeeds.as_view(), name='edit_feeds'),
   path('export_opml', view=ExportOpml.as_view(), name='export_opml'),
   path('update', view=UpdateItem.as_view(), name='update_item'),
]

dFeed/feedreader/models.py
from django.db import models
from django.utils import timezone
import datetime

class OptionsManager(models.Manager):
    def get_options(self):
        options = Options.objects.all()
        if options:
            options = options[0]
        else:  # Create options row with default values
            options = Options.objects.create()
        return options


class Options(models.Model):
    """
    Options controlling feedreader behavior

    :Fields:

        number_initially_displayed : integer
            Number of entries, from all feeds, initially displayed on webpage.
        number_additionally_displayed : integer
            Number of entries added to displayed results when scrolling down.
        max_entries_saved : integer
            Maximum number of entries to store for each feed.
    """
    number_initially_displayed = models.IntegerField(default=10)
    number_additionally_displayed = models.IntegerField(default=5)
    max_entries_saved = models.IntegerField(default=100)

    objects = models.Manager()
    manager = OptionsManager()

    class Meta:
        verbose_name_plural = "options"

    def __str__(self):
        return u'Options'


class Group(models.Model):
    """
    Group of feeds.

    :Fields:

        name : char
            Name of group.
    """
    name = models.CharField(max_length=250, unique=True)

    class Meta:
        ordering = ['name']

    def __str__(self):
        return self.name

    def num_unread_entries(self):
        return Entry.objects.filter(feed__group=self, read_flag=False).count()


class Feed(models.Model):
    """
    Feed information.

    :Fields:

        title : char
            Title of feed.
        xml_url : char
            URL of xml feed.
        link : char
            URL of feed site.
        description : text
            Description of feed.
        updated_time : date_time
            When feed was last updated.
        last_polled_time : date_time
            When feed was last polled.
        group : ForeignKey
            Group this feed is a part of.
    """
    title = models.CharField(max_length=2000, blank=True, null=True)
    xml_url = models.CharField(max_length=255, unique=True)
    link = models.CharField(max_length=2000, blank=True, null=True)
    description = models.TextField(blank=True, null=True)
    published_time = models.DateTimeField(blank=True, null=True)
    last_polled_time = models.DateTimeField(blank=True, null=True)
    group = models.ForeignKey(Group, blank=True, null=True, on_delete=models.SET_NULL)

    class Meta:
        ordering = ['title']

    def __str__(self):
        return self.title or self.xml_url

    def num_unread_entries(self):
        return Entry.objects.filter(feed=self, read_flag=False).count()


    def save(self, *args, **kwargs):
        """Poll new Feed"""
        try:
            Feed.objects.get(xml_url=self.xml_url)
            super(Feed, self).save(*args, **kwargs)
        except Feed.DoesNotExist:
            super(Feed, self).save(*args, **kwargs)
            from feedreader.utils import poll_feed

            poll_feed(self)

    def was_published_recently(self):
        return self.published_time.date() >= timezone.now() - datetime.timedelta(days=1)


class EntryManager(models.Manager):
    def num_unread(self):
        return Entry.objects.filter(read_flag=False).count()


class Entry(models.Model):
    """
    Feed entry information.

    :Fields:

        feed : ForeignKey
            Feed this entry is a part of.
        title : char
            Title of entry.
        link : char
            URL of entry.
        description : text
            Description of entry.
        updated_time : date_time
            When entry was last updated.
    """
    feed = models.ForeignKey(Feed, on_delete=models.CASCADE)
    title = models.CharField(max_length=2000, blank=True, null=True)
    link = models.CharField(max_length=2000)
    description = models.TextField(blank=True, null=True)
    published_time = models.DateTimeField(auto_now_add=True)
    read_flag = models.BooleanField(default=False)

    class Meta:
        ordering = ['-published_time']
        verbose_name_plural = 'entries'

    def __str__(self):
        return self.title

    objects = models.Manager()
    manager = EntryManager()

dFeed/feedreader/forms.py
from xml.etree import ElementTree

from django import forms

from feedreader.models import Feed, Group


class StringSearchForm(forms.Form):
    """
    Allow user to enter a string to search the for matching entries.
    """
    feedreader_search_string = forms.CharField()


class AddFeedsForm(forms.Form):
    """
    Add feeds individually or using an OPML file.
    """
    feed_url = forms.CharField(required=False)
    feed_group = forms.ModelChoiceField(queryset=Group.objects.all(), required=False)
    new_group = forms.CharField(required=False)
    opml_file = forms.FileField(required=False)

    def clean_feed_url(self):
        """Check new feed url not on database."""
        feed_url = self.cleaned_data['feed_url']
        try:
            Feed.objects.get(xml_url=feed_url)
            raise forms.ValidationError('Feed already exists')
        except Feed.DoesNotExist as e:
            pass
        return feed_url

    def clean_new_group(self):
        """Check new Group not on database."""
        new_group = self.cleaned_data['new_group']
        try:
            Group.objects.get(name=new_group)
            raise forms.ValidationError('Group already exists')
        except Group.DoesNotExist as e:
            pass
        return new_group

    def clean_opml_file(self):
        """Check OPML file contents."""
        opml_file = self.cleaned_data['opml_file']
        if opml_file:
            try:
                opml_tree = ElementTree.parse(opml_file)
            except ElementTree.ParseError as e:
                raise forms.ValidationError('Error Parsing OPML file: %s' % e.msg)
            return opml_tree

dFeed/feedreader/views.py
from __future__ import absolute_import

import json

from xml.etree import ElementTree
from xml.dom import minidom

from django.apps import apps
from django.urls import reverse_lazy
from django.http import HttpResponse
from django.views.generic import ListView, FormView, TemplateView, View

from braces.views import LoginRequiredMixin

from .constants import LOGOUT_URL
from .forms import AddFeedsForm, StringSearchForm
from .models import Group, Feed, Entry, Options
from .utils import build_context


class NumbersUnread(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        """Count numbers of unread entries, return in json object"""
        context = {'unread_total': Entry.manager.num_unread()}
        groups = Group.objects.all()
        for group in groups:
            num_unread = group.num_unread_entries()
            context['unread_group%s' % (group.id)] = num_unread
            context['unread_group_button%s' % (group.id)] = num_unread
        feeds = Feed.objects.all()
        for feed in feeds:
            context['unread_feed%s' % (feed.id)] = feed.num_unread_entries()
        return HttpResponse(json.dumps(context), content_type='application/json')


class EntryList(LoginRequiredMixin, ListView):
    """List of Entries"""
    model = Entry
    template_name = 'feedreader/entry_list.html'
    extra_context = {}

    def dispatch(self, request, *args, **kwargs):
        self.extra_context = build_context(request)
        self.queryset = self.extra_context['entry_list']
        return super(EntryList, self).dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(EntryList, self).get_context_data(**kwargs)
        self.extra_context.update(context)
        return self.extra_context


class MarkEntryRead(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        entry_id = request.GET.get('entry_id', None)
        if entry_id:
            try:
                entry = Entry.objects.get(pk=entry_id)
                if entry.read_flag == False:
                    entry.read_flag = True
                    entry.save()
            except Entry.DoesNotExist:
                pass
        return HttpResponse('')


class FeedList(LoginRequiredMixin, ListView):
    """List of Feeds by Group and those in no Group"""
    model = Group
    template_name = 'feedreader/feed_list.html'
    extra_context = {}

    def dispatch(self, request, *args, **kwargs):
        self.extra_context = build_context(request)
        return super(FeedList, self).dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(FeedList, self).get_context_data(**kwargs)
        context['logout_url'] = LOGOUT_URL
        context['no_group'] = Feed.objects.filter(group=None)
        self.extra_context.update(context)
        return self.extra_context


class Search(LoginRequiredMixin, TemplateView):
    """
    Simple string search.

    Display entries with titles and/or descriptions which
    contain the string searched for.
    """
    template_name = 'feedreader/search_results.html'

    def get(self, request, *args, **kwargs):
        context = self.get_context_data(**kwargs)
        form = StringSearchForm(request.GET)
        search_string = form.cleaned_data['feedreader_search_string'] if form.is_valid() else ''
        context['feedreader_search_string'] = search_string
        context['logout_url'] = LOGOUT_URL
        if len(search_string) < 3:
            context['too_small'] = True
        else:
            title_matches = Entry.objects.filter(title__icontains=search_string)
            description_matches = Entry.objects.filter(description__icontains=search_string)
            context['title_matches'] = title_matches
            context['description_matches'] = description_matches
        return self.render_to_response(context)


class EditFeeds(LoginRequiredMixin, FormView):
    """
    Edit feed subscriptions
    """
    template_name = 'feedreader/edit_feeds.html'
    form_class = AddFeedsForm
    success_url = reverse_lazy('feedreader:feed_list')

    def get_context_data(self, **kwargs):
        context = super(EditFeeds, self).get_context_data(**kwargs)
        context['logout_url'] = LOGOUT_URL
        context['groups'] = Group.objects.select_related().all()
        context['no_group'] = Feed.objects.filter(group=None)
        context['feedreader_options'] = Options.manager.get_options()
        return context

    def form_valid(self, form):
        feed_url = form.cleaned_data.get('feed_url')
        feed_group = form.cleaned_data.get('feed_group')
        if feed_url:
            feed = Feed.objects.create(xml_url=feed_url)
            if feed_group:
                feed.group = feed_group
                feed.save()
        new_group = form.cleaned_data.get('new_group')
        if new_group:
            group = Group.objects.create(name=new_group)
        tree = form.cleaned_data.get('opml_file')
        group = None
        if tree:
            for node in tree.iter('outline'):
                name = node.attrib.get('text')
                url = node.attrib.get('xmlUrl')
                if name and url:
                    try:
                        feed = Feed.objects.get(xml_url=url)
                    except Feed.DoesNotExist:
                        Feed.objects.create(xml_url=url, group=group)
                else:
                    group, created = Group.objects.get_or_create(name=name)
        return self.render_to_response(self.get_context_data(form=form))


class ExportOpml(LoginRequiredMixin, View):
    """
    Return feed subscriptions in OPML format.
    """

    def get(self, request, *args, **kwargs):
        root = ElementTree.Element('opml')
        root.set('version', '2.0')
        head = ElementTree.SubElement(root, 'head')
        title = ElementTree.SubElement(head, 'title')
        title.text = 'Feedreader Feeds'
        body = ElementTree.SubElement(root, 'body')

        feeds = Feed.objects.filter(group=None)
        for feed in feeds:
            feed_xml = ElementTree.SubElement(body,
                                              'outline',
                                              {'type': 'rss',
                                               'text': feed.title,
                                               'xmlUrl': feed.xml_url,
                                              }
            )

        groups = Group.objects.all()
        for group in groups:
            group_xml = ElementTree.SubElement(body,
                                               'outline',
                                               {'text': group.name,
                                               }
            )
            feeds = Feed.objects.filter(group=group)
            for feed in feeds:
                feed_xml = ElementTree.SubElement(group_xml,
                                                  'outline',
                                                  {'type': 'rss',
                                                   'text': feed.title,
                                                   'xmlUrl': feed.xml_url,
                                                  }
                )
        response = HttpResponse(content_type='text/xml')
        response['Content-Disposition'] = 'attachment; filename="feedreader.opml"'
        response.write(minidom.parseString(ElementTree.tostring(root, 'utf-8')).toprettyxml(indent="  "))
        return response


class UpdateItem(LoginRequiredMixin, View):
    """
    Update value in database.
    @param request: POST includes identifier and new value.

    @return Empty response.
    """

    def post(self, request, *args, **kwargs):
        identifier = request.POST.get('identifier', None)
        data_value = request.POST.get('data_value', None)
        if identifier:
            app_label, model_name, fieldname, primary_key = identifier.split('-')
            model = apps.get_model(app_label, model_name)
            if primary_key.isdigit():
                item = model.objects.get(pk=primary_key)
                if fieldname == 'delete':
                    item.delete()
                else:
                    field = model._meta.get_field(fieldname)
                    field_type = field.get_internal_type()
                    if field_type == 'BooleanField':
                        data_value = data_value == 'true'
                    elif field_type == 'ForeignKey':
                        if data_value:
                            data_value = field.remote_field.model.objects.get(pk=data_value)
                            setattr(item, fieldname, data_value)
                        else:
                            setattr(item, fieldname, None)
                    else:
                        setattr(item, fieldname, data_value)
                    item.save()
        return HttpResponse('')

dFeed/feedreader/templates/feedreader/feed_list.html
{% extends "base.html" %}

{% load i18n staticfiles %}

{% block extra_head %}
    <style type="text/css">
        #menu {margin-bottom: 1em;}
        .mark_read_request {font-weight:bold;}
        .poll_request {text-decoration:none;}
        p.feedreader_menu {font-size: small; margin: 0;}
        p.feedreader_subtitle {font-size: small;}
        #content {width: 80%;}
        .feed_entry {padding: 0.2em 0.5em; margin: 0.5em; border: 1px solid #046; border-radius: 1em;}
        .read_entry {color:#888;}
        #feed_entry_search {margin-top: 1em;}
        #spinner {position: fixed; top: 50%; left: 50%; margin-top: -64px; margin-left: -64px; z-index: 3;}
        #import_opml_label {color:#046; text-decoration:underline; cursor:pointer;}
    </style>
    <script type="text/javascript">
        function get_feedreader_filter(elem, current_filter) {
            if ($(elem).attr('id') == 'show_read') {
                var feedreader_filter = current_filter.group_id+'&'+current_filter.feed_id;
                if ($(elem).prop('checked')) {
                    feedreader_filter +='&show_read_flag=1';
                };
            }
            else {
                var group_id = $(elem).parents('div.group').attr('id');
                var feed_id = $(elem).parents('div.feed').attr('id');
                var feedreader_filter = '';
                if (group_id != null) {
                    feedreader_filter = group_id;
                }
                if (feed_id != null) {
                    if (feedreader_filter != '') {feedreader_filter += '&';}
                    feedreader_filter += feed_id;
                };
                if ($(elem).hasClass('poll_request')) {
                    if (feedreader_filter != '') {feedreader_filter += '&';}
                    feedreader_filter += 'poll_flag=1';
                };
                if ($(elem).hasClass('mark_read_request')) {
                    if (feedreader_filter != '') {feedreader_filter += '&';}
                    feedreader_filter += 'mark_read_flag=1';
                };
                if ($('#show_read').prop('checked')) {
                    if (feedreader_filter != '') {feedreader_filter += '&';}
                    feedreader_filter +='show_read_flag=1';
                };
            }
            return feedreader_filter
        };
        function populate_unread_nums() {
            $.get('{% url 'feedreader:num_unread' %}',
                function(json) {
                    $.each(json, function(key, value) {
                        if (value == 0) {
                            $('#'+key).text('');
                        }
                        else {
                            $('#'+key).text('('+value+')');
                        }
                    });
                }
            )
        };
        function mark_read_on_click() {
            $('.feed_entry').not('.read_entry').mousedown(function() {
                // Mark entry as read on click
                var entry_id = $(this).attr('id');
                var request_elem = this;
                $.ajax({url:'{% url 'feedreader:mark_entry_read' %}?'+entry_id,
                    success:function(){
                        $(request_elem).addClass('read_entry');
                        populate_unread_nums();
                        mark_read_on_click();
                        $(request_elem).off('mousedown');
                    }});
            });
        };
        $(function() {
            var current_filter = {
                group_id: 'group_id=0',
                feed_id: 'feed_id=0'
            };
            $('a.load_request').click(function(e) { // Disable links
                e.preventDefault();
            });
            $(document).hide().ajaxStart(function() {$('#spinner').show();})
                                .ajaxStop(function() {$('#spinner').hide();});
            $('.load_request').click(function() {
                var request_elem = this;
                $('#entries').load('{% url 'feedreader:entry_list' %}',
                    get_feedreader_filter(this, current_filter),
                    function () {
                        populate_unread_nums();
                        mark_read_on_click();
                        if ($(request_elem).attr('id') != 'show_read') {
                            group_id = $(request_elem).parents('div.group').attr('id');
                            if (group_id == null) {group_id = 'group_id=0';}
                            current_filter.group_id = group_id;
                            feed_id = $(request_elem).parents('div.feed').attr('id');
                            if (feed_id == null) {feed_id = 'feed_id=0';}
                            current_filter.feed_id = feed_id;
                        }
                    }
                )
            });
            $(window).scroll(function() {
                if ($(window).scrollTop() + $(window).height() >= $(document).height()) {
                    // Has reached bottom of the page
                    if ($('#no_entries').length == 0) {
	                    $('#entries > .feed_entry').not('.read_entry').addClass('read_entry').off('mousedown');
	                    var entry_id = $('#entries > .feed_entry').last().attr('id');
	                    var feedreader_filter = current_filter.group_id+'&'+current_filter.feed_id+'&'+entry_id;
	                    if ($('#show_read').prop('checked')) {
	                        feedreader_filter += '&show_read_flag=1';
	                    };
	                    if (entry_id == null) {entry_id = '';}
	                    $.get('{% url 'feedreader:entry_list' %}',
	                        feedreader_filter,
	                        function (data) {
	                            $('#entries').append(data);
	                            populate_unread_nums();
	                            mark_read_on_click();
	                        }
	                    );
	                }
                }
            });
            populate_unread_nums();
            mark_read_on_click();
            {% for group in group_list %}
                $('#group_{{ group.id }}_show').click(function() {
                    $('#group_{{ group.id }}_feeds').show('slow', function() {});
                    $('#group_{{ group.id }}_show').hide();
                    $('#group_{{ group.id }}_hide').show();
                });
                $('#group_{{ group.id }}_hide').click(function() {
                    $('#group_{{ group.id }}_feeds').hide('slow', function() {});
                    $('#group_{{ group.id }}_show').show();
                    $('#group_{{ group.id }}_hide').hide();
                });
                $('#group_{{ group.id }}_feeds').hide();
                $('#group_{{ group.id }}_hide').hide();
            {% endfor %}
            $('#all_entries_header').click(function() {
                {% for group in group_list %}
                    $('#group_{{ group.id }}_feeds').hide();
                    $('#group_{{ group.id }}_show').show();
                    $('#group_{{ group.id }}_hide').hide();
                {% endfor %}
            });
        });
    </script>
{% endblock %}

{% block title %}{{ site.domain }}: {% trans 'Feed Reader' %}{% endblock %}

{% block nav_path %}<a href="/">{{ site.domain }}</a> &rsaquo; {% trans 'Feed Reader' %}{% endblock %}

{% block content %}
    <h1>{% trans 'Feed Reader' %}</h1>
    <div id="menu" style="width:20%;float:left">
        <p>
            <input id="show_read"
                class="load_request"
                type="checkbox"
                name="{% trans 'Show Stories Already Read' %}">
            {% trans 'Show Read Stories' %}
        </p>
        <h3 id="all_entries_header">
            <a class="load_request"
                href="{% url 'feedreader:feed_list' %}"
                title="{% trans 'Show All feeds' %}">{% trans 'All Entries' %}</a>
            <span
                id="unread_total"
                title="{% trans 'Mark as Read' %}"
                class="load_request mark_read_request">
            </span>
        </h3>
        {% for group in group_list %}
            <div id="group_id={{ group.id }}" class="group">
                <h3>
                    <span id="group_{{ group.id }}_show">&#9658;</span>
                    <span id="group_{{ group.id }}_hide">&#9660;</span>
                    <a class="load_request"
                        href="{% url 'feedreader:feed_list' %}?group_id={{ group.id }}"
                        title="{% trans 'Show All' %} {{ group.name }} feeds">{{ group.name }}</a>&nbsp;<a class="load_request poll_request"
                        href="{% url 'feedreader:feed_list' %}?group_id={{ group.id }}&poll_flag=1"
                        title="{% trans 'Poll All' %} {{ group.name }} feeds">&darr;</a>
                    <span id="unread_group{{group.id}}"
                        class="load_request mark_read_request"
                        title="{% trans 'Mark as Read' %}">
                    </span>
                </h3>
                <div id="group_{{ group.id }}_feeds">
                    {% for feed in group.feed_set.all %}
                        <div id="feed_id={{ feed.id }}" class="feed">
                            <p class="feedreader_menu">
                                <a class="load_request"
                                    href="{% url 'feedreader:feed_list' %}?feed_id={{ feed.id }}"
                                    title="{{ feed.description|safe }}">{{ feed.title|safe }}</a>&nbsp;<a class="load_request poll_request"
                                    href="{% url 'feedreader:feed_list' %}?feed_id={{ feed.id }}&poll_flag=1"
                                    title="{% trans 'Poll' %} {{ feed.title|safe }} feed">&darr;</a>
                                <span id="unread_feed{{feed.id}}"
                                    class="load_request mark_read_request"
                                    title="{% trans 'Mark as Read' %}">
                                </span>
                            </p>
                        </div>
                    {% endfor %}
                </div>
            </div>
        {% endfor %}
        {% for feed in no_group %}
            <div id="feed_id={{ feed.id }}" class="feed">
                <p>
                    <a class="load_request"
                        href="{% url 'feedreader:feed_list' %}?feed_id={{ feed.id }}"
                        title="{{ feed.description|safe }}">{{ feed.title|safe }}</a>&nbsp;<a class="load_request poll_request"
                        href="{% url 'feedreader:feed_list' %}?feed=_id{{ feed.id }}&poll_flag=1"
                        title="{% trans 'Poll' %} {{ feed.title|safe }} feed">&darr;</a>
                    <span id="unread_feed{{feed.id}}"
                        class="load_request mark_read_request"
                        title="{% trans 'Mark as Read' %}">
                    </span>
                </p>
            </div>
        {% endfor %}
        <form name="input" action="{% url 'feedreader:search' %}" method="get" style="padding-right:1em;">
            <input id="feed_entry_search" type="text" tabindex="2" size="10"
                style="color:{% if feedreader_search_string %}#000;{% else %}#ccc{% endif %};"
                name="feedreader_search_string" title="{% trans 'Search Feeds' %}" class="text"
                value="{% if feedreader_search_string %}{{ feedreader_search_string }}{% else %}{% trans 'Search Feeds' %}{% endif %}"/>
        </form>
    </div>
    <div id="entries" style="width:75%;float:left;padding-left:1em;">
        {% include "feedreader/entry_list.html" %}
    </div>
    <div style="clear:both"></div>
    <div id="spinner">
        <img src="{% static 'spinner.gif' %}" alt="{% trans 'Please Wait' %}" title="{% trans 'Please Wait' %}" />
    </div>
{% endblock %}

{% block footer %}
    <p>
        <a href="#" title="{% trans 'Back to Top' %}">{% trans 'Top' %}</a>;
        <a href="{% url 'feedreader:edit_feeds' %}" title="{% trans 'Edit Feeds' %}">{% trans 'Edit' %}</a>;
        <a href="{{ logout_url }}">{% trans 'Logout' %}</a>.
    </p>
{% endblock %}

dFeed/feedreader/templates/feedreader/search_results.html
{% extends "base.html" %}

{% load i18n %}

{% block extra_head %}
    <style type="text/css">
        #content {width: 80%;}
    </style>
{% endblock %}

{% block title %}{{ site.domain }}: {% trans 'Feed Reader Search Results' %}{% endblock %}

{% block nav_path %}
    <a href="/">{{ site.domain }}</a> &rsaquo;
    <a href="{% url 'feedreader:feed_list' %}">Feed Reader</a> &rsaquo;
    Search Results
{% endblock %}

{% block content %}
    <div style="padding-top:0.5em;">
        <form name="input" action="{% url 'feedreader:search' %}" method="get" style="padding-right:1em;">
            New Search:
            <input type="text" tabindex="2" size="10"
                {% if feedreader_search_string %}style="color:#000;"{% else %}style="color:#ccc;"{% endif %}
                name="feedreader_search_string" title="Search Feeds" class="text"
                value="{% if feedreader_search_string %}{{ feedreader_search_string }}{% else %}Search Feeds{% endif %}"/>
        </form>
    </div>

    {% if too_small %}
        <h1>{% trans 'No Search Results' %}</h1>
        <p>{% trans 'Search string too small' %}: "{{ feedreader_search_string }}".</p>
    {% else %}
        <h1>{% trans 'Search Results for' %}: "{{ feedreader_search_string }}"</h1>
        <h2>{% trans 'Title Matches' %}</h2>
        {% if title_matches %}
            <ol>
            {% for entry in title_matches %}
                <li>
                    <a href="{{ entry.link }}">{{ entry.title|safe }}</a>
                    ({{ entry.feed.title|safe }}; {{ entry.published_time}}; {{ entry.published_time|timesince }} ago)
                </li>
            {% endfor %}
            </ol>
        {% else %}
            <p>{% trans 'No matching titles found.' %}</p>
        {% endif %}
        <h2>{% trans 'Description Matches' %}</h2>
        {% if description_matches %}
            <ol>
            {% for entry in description_matches %}
                <li>
                    <a href="{{ entry.link }}">{{ entry.title|safe }}</a>
                    ({{ entry.feed.title|safe }}; {{ entry.published_time}}; {{ entry.published_time|timesince }} ago):
                    <p>{{ entry.description|safe }}</p>
                </li>
            {% endfor %}
            </ol>
        {% else %}
            <p>{% trans 'No matching content found.' %}</p>
        {% endif %}
    {% endif %}
{% endblock %}

{% block footer %}
    <p>
        <a href="#" title="{% trans 'Back to Top' %}">{% trans 'Top' %}</a>;
        <a href="{% url 'admin:feedreader_feed_changelist' %}" title="{% trans 'Edit Feeds' %}">{% trans 'Admin' %}</a>;
        <a href="{{ logout_url }}">{% trans 'Logout' %}</a>.
    </p>
{% endblock %}